; Thanks for downloading the bugfix mod! Please be sure to report any issues at our GitHub page below:
; https://github.com/ShizCalev/MGS2-Demastered-Substance-Edition

[Update Notifications]
; Provides in-game notifications if an update for the MGS2 Demastered Substance Edition Updates is available.
Check For MGS2 Demastered Substance Edition Updates = true
