; Thanks for downloading the bugfix mod! Please be sure to report any issues at our GitHub page below:
; https://github.com/ShizCalev/MGS3-Demastered-Subsistence-Edition

[Update Notifications]
; Provides in-game notifications if an update for the MGS3 Demastered Subsistence Edition Updates is available.
Check For MGS3 Demastered Subsistence Edition Updates = true
